### ISSUE TITLE
not working in production

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/c9-wakatime#2]
The Cloud9 plugin only works in dev mode when locally running the Cloud9 sdk.

It doesn't work in production yet. More info here:
https://groups.google.com/d/msg/cloud9-sdk/d7w5KaPEXI0/l5cx6onNAQAJ

**Comment by alanhamlett** [comment]
Fixed on March 10th.

**Comment by rw251** [comment]
I still don't get prompted for an api key when using v2.0.3.

![example](https://cloud.githubusercontent.com/assets/7155684/14018417/9aea6530-f1c5-11e5-859c-5c7367cdd3b5.png)

Let me know if there's anymore debugging info I can provide.

**Comment by alanhamlett** [comment]
@rw251 are there any wakatime related errors in your Browser Console window when installing the plugin?

**Comment by rw251** [comment]
Yes looks like there is. Below is copied from the browser console:

```
PubSub message: Object {channel: "/events/p/503524/37155", type: "package", action: "install", body: Object}
workspace-php.js:25154 PubSub package API message Object {channel: "/events/p/503524/37155", type: "package", action: "install", body: Object}
workspace-php.js:24799 Error: Plugin is missing the setup function {"wakatime":{"packagePath":"plugins/wakatime/wakatime"},"name":"wakatime","version":"2.0.3","apikey":"wAhcDqPc4t+95pIe6EHDekJY6R8="}
    at https://cdn.c9.io/nc-3.1.1947-5a3efd86/config/workspace-php.js:183:137
    at Array.forEach (native)
    at checkConfig (https://cdn.c9.io/nc-3.1.1947-5a3efd86/config/workspace-php.js:183:51)
    at https://cdn.c9.io/nc-3.1.1947-5a3efd86/config/workspace-php.js:216:20
    at https://cdn.c9.io/nc-3.1.1947-5a3efd86/config/workspace-php.js:270:95
    at _require (https://cdn.c9.io/nc-3.1.1947-5a3efd86/config/workspace-php.js:63:27)
    at req (https://cdn.c9.io/nc-3.1.1947-5a3efd86/config/workspace-php.js:45:45)
    at resolveConfig (https://cdn.c9.io/nc-3.1.1947-5a3efd86/config/workspace-php.js:268:4)
    at Object.resolveConfig (https://cdn.c9.io/nc-3.1.1947-5a3efd86/config/workspace-php.js:265:91)
    at Architect.loadAdditionalPlugins (https://cdn.c9.io/nc-3.1.1947-5a3efd86/config/workspace-php.js:214:222)
```

**Comment by alanhamlett** [comment]
Just updated the issue with Cloud9:

https://groups.google.com/forum/#!msg/cloud9-sdk/d7w5KaPEXI0/l5cx6onNAQAJ

**Comment by nightwing** [comment]
@rw251 do you still see the issue? this may be a race condition in the code loading the plugin for the first time.

**Comment by rw251** [comment]
Yes I still see this. I got the same error on 3 different c9 vm environments as well.

**Comment by ghost** [comment]
I am also experiencing the issue where c9 does not prompt for the API key.  However, the install clears successfully and I see no relevant errors on the Firefox Browser Console.

`syntax error 2803125:1:1`
`PubSub message: Object { channel: "/events/p/2803125/934574", type: "package", action: "uninstall", body: Object } workspace-html5.js:7880:92`
`PubSub message: Object { channel: "/events/p/2803125/934574", type: "package", action: "install", body: Object } workspace-html5.js:7880:92`
`no element found`

**Comment by samudary** [comment]
Hi there,

Having the same issue when installing on C9. No prompt for the API key.

**Comment by nightwing** [comment]
are you installing with `?debug=2` or without? `?debug=2` is only for development.

**Comment by rw251** [comment]
I'm not installing with `?debug=2`.

**Comment by ghost** [comment]
The production version of wakatime, when installed in **Debug mode** with `c9 install wakatime` works, with the Dialog box popping up.  It also appears in C9>Preferences>Plugin Manager>Installed Plugins.

However, when working on non-debug mode, wakatime is not present in Installed Plugins.  Running `c9 install wakatime` yields an "this folder already exists" error.

**Comment by ghost** [comment]
I was able to get `c9 install wakatime` to work while in **non-debug** mode by going into `C9 Gear/Preferences Icon > Experimental > SDK` and turning on all three **SDK** options, `Load Custom Plugin` and `Load Plugin from Workspace` before running `c9 install wakatime`.

**Comment by rw251** [comment]
Yes that works for me too. I had previously installed wakatime and after enabing `Load Custom Plugin` and `Load Plugin from Workspace`, then refreshing the page led to the Email/Api pop up appearing.

**Comment by chocoelho** [comment]
I'm able to use wakatime when in debug mode, but when trying to install it normally, it throws this error:

```
<user>:~/workspace $ c9 install wakatime --force
Unknown Error getting api.c9.io/packages/wakatime/versions/3.0.2/download?access_token=<my_token>
<user>:~/workspace $ c9 install wakatime
WARNING: Directory not empty: /home/ubuntu/.c9/plugins/wakatime. Use --force to overwrite.
```

**Comment by chocoelho** [comment]
I've enabled both options `Load Custom Plugin` and `Load Plugin from Workspace`, but still, nothing happens(just the error message).

**Comment by emilgodsk** [comment]
Wakatime not installing on cloud9 - getting following errors:

"username":~/workspace $ c9 install wakatime
WARNING: Directory not empty: /home/ubuntu/.c9/plugins/wakatime. Use --force to overwrite.

"username":~/workspace $ c9 install wakatime --force
Unknown Error getting api.c9.io/packages/wakatime/versions/3.0.2/download?access_token=xxxxxxxxxxxxx:500

19 oct. 2016 - 13:50

**Comment by spences10** [comment]
Is this still broken? I tried installing yesterday and got the same errors as @egodsk and @chocoelho 

Read through the Google groups posts and it doesn't seem like anyone got anywhere with it, is that a fair assumption?

**Comment by alanhamlett** [comment]
#8 has manual install instructions that work, but only when your C9 IDE is in debug mode. I'll add those instructions to the readme soon.

**Comment by arishuynhvan** [comment]
Hi, this is still broken as of today

**Comment by alanhamlett** [comment]
@arishuynhvan have you tried the manual install steps?

**Comment by arishuynhvan** [comment]
Thanks for making the manual install instructions. I've tried and it seemed to have installed, but somehow, the status was not updated in the wakatime dashboard when I work in c9 regardless of my debugging mode.

I think because I installed Wakatime extension for Chrome.
So I tried to launch c9 in Firefox, and the dashboard is now updated with Wakatime in the debug mode.
However, I think it may not update when I work in the non-debugging mode.

**Comment by alanhamlett** [comment]
These new install instructions should help:
https://github.com/wakatime/c9-wakatime#installation

(Thanks to Luciendub https://community.c9.io/t/allow-wakatime-in-normal-mode/14815)

**Comment by spences10** [comment]
So this still doesn't work in normal mode?

The instructions say you need it in debug mode, I amended my init script then restarted c9 and there was no prompt to enter my api key

I'm a bit confused as to how to get this to work still, do I need to flit between debug and normal mode?

Seems a bit hacky

**Comment by alanhamlett** [comment]
Debug mode should no longer be needed, using the latest instructions you can run the plugin in Normal mode.

**Comment by spences10** [comment]
Ok, when I 'restart' I use the restart button

![image](https://cloud.githubusercontent.com/assets/234708/24513893/5d165aa6-156a-11e7-92eb-241a9ce8cf56.png)

After that I'm not prompted to enter my API key
